apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: T25jZW5hY2lvMTY=
  MARIADB_PASSWORD: T25jZW5hY2lvMTY=
  MARIADB_DATABASE: Ym9va3Ntcw==
  MARIADB_USER: YmxhbmRldg==
