apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: T25jZW5hY2lvMTY= # Oncenacio16
  MARIADB_PASSWORD: T25jZW5hY2lvMTY= # Oncenacio16
  MARIADB_DATABASE: Ym9va3Ntcw== # booksms
  MARIADB_USER: YmxhbmRldg= # blandev
