apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-leer-deployment 
  labels:
    app: leer-app 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: leer-app 
  template:
    metadata:
      labels:
        app: leer-app 
    spec:
      containers:
      - name: microservicio-leer-container
        image: tu-usuario-dockerhub/microservicio-leer:v1 
        ports:
        - containerPort: 8080 
        env: 
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mariadb://mariadb-service:3306/TU_BASE_DE_DATOS" 
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials 
              key: MARIADB_USER        
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-credentials 
              key: MARIADB_PASSWORD    
